<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Categoria;
use AppBundle\Form\CategoriaType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categoria")
 */

class CategoriaController extends Controller
{
    /**
     * @Route("/nueva-categoria", name="nueva-categoria")
     */
    public function indexAction(Request $request)
    {
        $objCategoria = new Categoria();
        //Se crea el formulario
        $form = $this->createForm(CategoriaType::class, $objCategoria);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //Rellenamos el objeto Platillo
            $objCategoria = $form->getData();

            $file = $objCategoria->getFoto();
            //Cambiamos el nombre del archivo con la encriptacion md5
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            //Movemos la imagen al fichero configurado dentro del proyecto
            $file->move(
                $this->getParameter('uploads_directory'),
                $fileName
            );

            $objCategoria->setFoto($fileName);
            $objCategoria->setNombre($objCategoria->getNombre());
            $objCategoria->setDescripcion($objCategoria->getDescripcion());

            //Se almacena el platillo
            $em = $this->getDoctrine()->getManager();
            $em->persist($objCategoria);
            $em->flush();

            //dump($objPlatilo);die();

            return $this->redirectToRoute('homepage');
        }

        // replace this example code with whatever you need
        return $this->render('categoria/nuevo.html.twig', array(
            "form" => $form->createView()
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}