<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Ingrediente;
use AppBundle\Entity\Platillo;
use AppBundle\Form\PlatilloType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/platillo")
 */

class GestionPlatilloController extends Controller
{
    /**
     * @Route("/nuevo-platillo", name="nuevo-platillo")
     */
    public function indexAction(Request $request)
    {
        $objPlatilo = new Platillo();
        //Se crea el formulario
        $form = $this->createForm(PlatilloType::class, $objPlatilo);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //Rellenamos el objeto Platillo
            $objPlatilo = $form->getData();

            $file = $objPlatilo->getFoto();
            //Cambiamos el nombre del archivo con la encriptacion md5
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            //Movemos la imagen al fichero configurado dentro del proyecto
            $file->move(
                $this->getParameter('uploads_directory'),
                $fileName
            );
            //dump($objPlatilo->getIngredientes());die();
            $objPlatilo->setFoto($fileName);
            $objPlatilo->setNombre($objPlatilo->getNombre());
            $objPlatilo->setDescripcion($objPlatilo->getDescripcion());
            /*foreach ($objPlatilo->getIngredientes() as $ingrediente){
                $newIngrediente = new Ingrediente();
                $newIngrediente->setId($ingrediente->getId());
                $newIngrediente->setNombre($ingrediente->getNombre());
                $objPlatilo->addIngrediente($ingrediente);
            }*/
            //$objPlatilo->addIngrediente($objPlatilo->getIngredientes());
            $objPlatilo->setFechaCreacion(new \DateTime());
            $objPlatilo->setTop($objPlatilo->getTop());

            //Se almacena el platillo
            $em = $this->getDoctrine()->getManager();
            $em->persist($objPlatilo);
            $em->flush();

            //dump($objPlatilo);die();

            return $this->redirectToRoute('homepage');
        }

        // replace this example code with whatever you need
        return $this->render('platillo/nuevoPlatillo.html.twig', array(
            "form" => $form->createView()
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}