<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Ingrediente;
use AppBundle\Form\IngredienteType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ingrediente")
 */

class IngredienteController extends Controller
{
    /**
     * @Route("/nuevo-ingrediente", name="nuevo-ingrediente")
     */
    public function indexAction(Request $request)
    {
        $ingrediente = new Ingrediente();
        //Se crea el formulario
        $form = $this->createForm(IngredienteType::class, $ingrediente);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //Rellenamos el objeto Platillo
            $ingrediente = $form->getData();

            $ingrediente->setNombre($ingrediente->getNombre());

            //Se almacena el platillo
            $em = $this->getDoctrine()->getManager();
            $em->persist($ingrediente);
            $em->flush();

            return $this->redirectToRoute('ingredientes');
        }

        // replace this example code with whatever you need
        return $this->render('ingrediente/ing-nuevo.html.twig', array(
            "form" => $form->createView()
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}